# Gateway config docs: https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/
# Circuit Breaker (filter) docs: https://cloud.spring.io/spring-cloud-circuitbreaker/reference/html/spring-cloud-circuitbreaker.html
server:
    port: 8090
    

spring:
  cloud:
    gateway:
      routes:
      - id: base-repo
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/dataresources/**
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/notfound
      - id: metastore_documents
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/metadata/**
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/notfound      
      - id: metastore_schemas
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/schemas/**
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/notfound
      - id: notfound_to_example_404
        uri: https://example.org
        predicates:
        - Path=/notfound
        filters:
        - RewritePath=/notfound, /
        - SetStatus=404
  boot:
    admin:
      client:
        url: http://localhost:8060
        username: admin
        password: admin-password
        instance:
          name: Gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
  info:
    env:
      enabled: true
# Interesting logging levels: https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#log-levels
logging:
  level:
    '[org.springframework.cloud.gateway]': INFO
    
    